### ISSUE TITLE
NOT available on play store

### ISSUE THREAD

**Issue by pbweb1969** [adrian/upm-android#36]
Hi ive used UPM for years, brilliant program! however im trying to install it on another android device, but cant find it on play store, and even following link from sourceford dosnt show the app. please help
Many thanks

**Comment by jaybeeAndMe** [comment]
I am also an long time user. Just got a new Android Phone & need to download from playstore, but it's not there.
Is there another location from which I can download? or could you please make it available on Playstore?
Thanks for a very useful app.

**Comment by simooooone** [comment]
Same problem. Android oreo - Huawei P10 lite from Repubblica di San Marino

**Comment by adrian** [comment]
I removed UPM from the play store some time ago as I no longer have the time to support it. I didn't feel it was fair to publish something that isn't supported.

I appreciate this has left existing users in a difficult position so I've republished UPM to the play store. I left a note explaining UPM is no longer supported and new users should look elsewhere.

It should be available in the play store in a few hours. According to Google,

> Updates to your app usually become available on Google Play within a few hours, but may sometimes take longer.

**Comment by pbweb1969** [comment]
thanks a lot, I appreciate you can support it anymore, but its such a great little app.
are you still accepting donations? 

    On Sunday, 18 November 2018, 20:45, Adrian Smith <notifications@github.com> wrote:
 

 Closed #36.—

**Comment by pbweb1969** [comment]
i meant cant 

    On Sunday, 18 November 2018, 19:06, Simone <notifications@github.com> wrote:
 

 Same problem. Android oreo - Huawei P10 lite from Repubblica di San Marino—

**Comment by Oloryn** [comment]
This has become an issue again in late 2021.  Any way an apk can be made available for side-loading?

**Comment by drbgfc** [comment]
Wouldn't it be possible to just pull this source and build it locally?
If someone does get around to it, maybe the repo could be forked and a release could be made and posted there.
If I get time maybe I'll do that. I've never used the android version yet though. Always just used the desktop version.

**Comment by adrian** [comment]
UPM is available in the Google Play store again. It was taken down a while back as I hadn't  completed some recent changes to the listing requirements. I submitted the updated details and the listing has been restored.

**Comment by Oloryn** [comment]
Thank you, Adrian, I appreciate it.
