### ISSUE TITLE
Sync with Dropbox stopped working

### ISSUE THREAD

**Issue by N3WWN** [adrian/upm-android#37]
I’m not sure if this is similar to the problem reported in #32 , but my Android UPM app stopped syncing with DropBox in the last week or so.

My DropBox app still works on my phone, but UPM 1.17 (22) states “Problem communicating with Dropbox” when I attempt to sync.  

UPM on my Mac still works just fine, though.

Thanks in advance!

**Comment by adrian** [comment]
Hi N3WWN.

I don't believe this is the same problem as that reported in https://github.com/adrian/upm-android/issues/32.

I've left a comment over on a [related thread on Sourceforge](https://sourceforge.net/p/upm/discussion/517033/thread/d85a9968b3/).

**Comment by N3WWN** [comment]
@adrian Thank you so much!

**Comment by adrian** [comment]
I've just released a new version of UPM (version 1.19) with a fix for the Dropbox syncing issue. This new version should be available as an upgrade in the play store over the next few hours.
