### ISSUE TITLE
UPM - Backup 

### ISSUE THREAD

**Issue by Spencie2010** [adrian/upm-android#38]
Android Phone model - Google Pixel 4a5G
Android Version 12
Link to issue on SourceForge website https://sourceforge.net/p/upm/discussion/517033/thread/d85a9968b3/?page=1&limit=25#ebcb/bdf3

Issue...
Syncing to DropBox - **_had_** been inoperative until recent UPM app update - **_now_** works fine.
Backup function - **_had_** been working until recent app update **_now_** I receive a message "problem performing file operation"

UPM preferences page screenshot attached 
![Screenshot_20220510-173601](https://user-images.githubusercontent.com/105321537/167726059-9e988a54-e536-4dee-8dbf-2ca9d571c91f.png)

**Comment by adrian** [comment]
This issue should be resolved in the UPM v1.20.

For updated backup/restore instructions see http://upm.sourceforge.net/upm_android_userguide.html#copy_db_to_new_device.
