### ISSUE TITLE
UPM "Problem performing file operation"

### ISSUE THREAD

**Issue by Caleb461** [adrian/upm-android#40]
+ Getting "Problem performing file operation" error when attempting to "Restore Database From Backup" using existing upm.db file in root folder of new phone:
Galaxy S22 Ultra
UPM version 1.19 (24)
Samsung UI 4.1
Android 12 
Android security patch 5/1/22
Google Play system update 4/1/22

+ Have used UPM since 2012 on the following phones: Galaxy Nexus, Galaxy S6, Galaxy S8, Galaxy S21U. Never had issue with "Backup" and "Restore" functions until now. 

+ Whenever I get a new phone, I typically perform "Backup" on existing phone to generate upm.db file in root folder, then copy that file from existing phone to root folder of new phone. Then I install UPM on new phone and "Restore Database From Backup". Has always worked great until now. 

+ After this Backup/Restore method resulted in "Problem performing file operation" on the new S22U, I used Samsung's "Smart Switch" to directly transfer the UPM app from my S21U to the new S22U. The good news is that it worked and I was able to launch UPM and access my database on the new S22U. The bad news is, when I tried to use "Backup" to create a new upm.db file on the new S22U, I got the same "Problem performing file operation" error. Doh!

+ So UPM cannot READ an EXISTING upm.db file, nor can it WRITE a NEW upm.db file. 

Hopefully this info helps you troubleshoot the issue, Adrian. THANK YOU for this awesome tool, and THANK YOU in advance for your help with figuring this out! Let me know if there is anything else I can do to help with troubleshooting. There's a $25 app donation for your time if you can fix this! 🙂

-Caleb 

.

**Comment by adrian** [comment]
This issue should be resolved in the UPM v1.20.

For updated backup/restore instructions see http://upm.sourceforge.net/upm_android_userguide.html#copy_db_to_new_device.
